nodeLinker: node-modules

packageExtensions:
  "@commitlint/load@*":
    dependencies:
      "@types/node": "*"
      "typescript": "*"
  "cosmiconfig-typescript-loader@*":
    dependencies:
      "@types/node": "*"
      "typescript": "*"
